// АВТОМАТИЧЕСКИ СГЕНЕРИРОВАННАЯ КЛАССИФИКАЦИЯ РАСТЕНИЙ
// На основе plant_catalog.json (228 растений)

const PLANT_SURVIVAL_CLASSIFICATION = {
  "plant_001": { id: "plant_001", name: "Абутилон", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_002": { id: "plant_002", name: "Агава", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_003": { id: "plant_003", name: "Адениум", score: 7, water: "moderate", light: "high", difficulty: "medium" },
  "plant_004": { id: "plant_004", name: "Алоказия Азлани", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_005": { id: "plant_005", name: "Алоказия Полли", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_006": { id: "plant_006", name: "Алоказия Регинула", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_007": { id: "plant_007", name: "Алоказия Таро", score: 5, water: "frequent", light: "medium", difficulty: "medium" },
  "plant_008": { id: "plant_008", name: "Алоказия Хетерофилла", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_009": { id: "plant_009", name: "Алоказия Шкура Дракона", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_010": { id: "plant_010", name: "Амарилис", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_011": { id: "plant_011", name: "Аморфофалус Коньяк", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_012": { id: "plant_012", name: "Анакампсерос Санрайз", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_013": { id: "plant_013", name: "Ананас Карликовый", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_014": { id: "plant_014", name: "Аспидастра", score: 9, water: "moderate", light: "low", difficulty: "easy" },
  "plant_015": { id: "plant_015", name: "Ахименез", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_016": { id: "plant_016", name: "Бамбук", score: 5, water: "frequent", light: "medium", difficulty: "medium" },
  "plant_017": { id: "plant_017", name: "Банан Карликовый Кавендиш", score: 5, water: "frequent", light: "high", difficulty: "medium" },
  "plant_018": { id: "plant_018", name: "Баухиния", score: 7, water: "moderate", light: "high", difficulty: "medium" },
  "plant_019": { id: "plant_019", name: "Бегония Бауэра Тайгер", score: 5, water: "moderate", light: "low", difficulty: "medium" },
  "plant_020": { id: "plant_020", name: "Бегония Коралловая", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_021": { id: "plant_021", name: "Бегония Макулата Радди", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_022": { id: "plant_022", name: "Бругмансия", score: 6, water: "frequent", light: "high", difficulty: "medium" },
  "plant_023": { id: "plant_023", name: "Бугенвиллия", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_024": { id: "plant_024", name: "Бугенвиллия", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_025": { id: "plant_025", name: "Бугенвиллия", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_026": { id: "plant_026", name: "Будлея Давида", score: 7, water: "moderate", light: "high", difficulty: "easy" },
  "plant_027": { id: "plant_027", name: "Вашингтония Веерная", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_028": { id: "plant_028", name: "Гастерия Армстронга", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_029": { id: "plant_029", name: "Гастерия Бородавчатая", score: 8, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_030": { id: "plant_030", name: "Гибискус Китайский", score: 5, water: "moderate", light: "high", difficulty: "medium" },
  "plant_031": { id: "plant_031", name: "Гибискус Сирийский Блю Шифон", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_032": { id: "plant_032", name: "Гибискус Текила Санрайз", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_033": { id: "plant_033", name: "Гилоцереус Волнистый", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_034": { id: "plant_034", name: "Гимнокалициум Михановича", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_035": { id: "plant_035", name: "Гинура", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_036": { id: "plant_036", name: "Глариоза Родшильда", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_037": { id: "plant_037", name: "Гранат Карликовый", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_038": { id: "plant_038", name: "Диффенбахия Сегуина", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_039": { id: "plant_039", name: "Драцена Окаймленная", score: 8, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_040": { id: "plant_040", name: "Жасмин Многоцветковый", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_041": { id: "plant_041", name: "Замиакулькас Рейвен", score: 8, water: "rare", light: "low", difficulty: "easy" },
  "plant_042": { id: "plant_042", name: "Замиокулькас", score: 10, water: "rare", light: "low", difficulty: "easy" },
  "plant_043": { id: "plant_043", name: "Каламондин", score: 5, water: "moderate", light: "high", difficulty: "medium" },
  "plant_044": { id: "plant_044", name: "Каланхоэ Блоссфельда", score: 7, water: "moderate", light: "high", difficulty: "easy" },
  "plant_045": { id: "plant_045", name: "Каланхоэ Войлочное Kalanchoe Tomentosa", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_046": { id: "plant_046", name: "Калатея Макояна", score: 4, water: "frequent", light: "medium", difficulty: "hard" },
  "plant_047": { id: "plant_047", name: "Калатея Орбифолия", score: 4, water: "frequent", light: "medium", difficulty: "hard" },
  "plant_048": { id: "plant_048", name: "Калатея Пинстрайп", score: 4, water: "frequent", light: "medium", difficulty: "hard" },
  "plant_049": { id: "plant_049", name: "Калла", score: 6, water: "frequent", light: "medium", difficulty: "medium" },
  "plant_050": { id: "plant_050", name: "Каллизия Розовая", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_051": { id: "plant_051", name: "Каллизия", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_052": { id: "plant_052", name: "Каллистемон Левис", score: 7, water: "moderate", light: "high", difficulty: "medium" },
  "plant_053": { id: "plant_053", name: "Камнеломка Плетеносная", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_054": { id: "plant_054", name: "Клеродендрум Уоллича Просперо", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_055": { id: "plant_055", name: "Колеус Разноцветный", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_056": { id: "plant_056", name: "Конфетное Дерево", score: 7, water: "moderate", light: "high", difficulty: "medium" },
  "plant_057": { id: "plant_057", name: "Кофе", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_058": { id: "plant_058", name: "Крассула Марнье.", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_059": { id: "plant_059", name: "Крассула Толстянка Денежное Дерево", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_060": { id: "plant_060", name: "Красула Перфората", score: 8, water: "rare", light: "medium", difficulty: "easy" },
  "plant_061": { id: "plant_061", name: "Красулла Толстянка Плауновидная", score: 8, water: "rare", light: "medium", difficulty: "easy" },
  "plant_062": { id: "plant_062", name: "Крестовник Крупноязычковый", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_063": { id: "plant_063", name: "Крестовник Роули", score: 8, water: "rare", light: "medium", difficulty: "easy" },
  "plant_064": { id: "plant_064", name: "Кришна Туласи Базелик", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_065": { id: "plant_065", name: "Ктенанта Amagris", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_066": { id: "plant_066", name: "Ктенанта Лубберса", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_067": { id: "plant_067", name: "Куркума", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_068": { id: "plant_068", name: "Лайм Пальчиковый", score: 5, water: "moderate", light: "high", difficulty: "medium" },
  "plant_069": { id: "plant_069", name: "Лимон", score: 5, water: "moderate", light: "high", difficulty: "medium" },
  "plant_070": { id: "plant_070", name: "Литопсы", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_071": { id: "plant_071", name: "Мандевилла", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_072": { id: "plant_072", name: "Маранта Керховена", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_073": { id: "plant_073", name: "Молочай Мили", score: 7, water: "moderate", light: "high", difficulty: "easy" },
  "plant_074": { id: "plant_074", name: "Молочай Тирукалли", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_075": { id: "plant_075", name: "Монстера Адансона", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_076": { id: "plant_076", name: "Монстера Деликатесная", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_077": { id: "plant_077", name: "Монстера Карстенианум.", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_078": { id: "plant_078", name: "Монстера Манки Маск", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_079": { id: "plant_079", name: "Мурданния Лориформис", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_080": { id: "plant_080", name: "Муррайя Метельчатая", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_081": { id: "plant_081", name: "Нематантус Грегариус", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_082": { id: "plant_082", name: "Нолина", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_083": { id: "plant_083", name: "Олеандр", score: 7, water: "moderate", light: "high", difficulty: "easy" },
  "plant_084": { id: "plant_084", name: "Олива", score: 8, water: "moderate", light: "high", difficulty: "easy" },
  "plant_085": { id: "plant_085", name: "Опунция Инжирная", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_086": { id: "plant_086", name: "Орхидея Ванда", score: 3, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_087": { id: "plant_087", name: "Орхидея Дендробиум", score: 3, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_088": { id: "plant_088", name: "Орхидея Лудизия Драгоценная", score: 3, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_089": { id: "plant_089", name: "Орхидея Одонтоглоссум", score: 3, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_090": { id: "plant_090", name: "Орхидея Пафиопедилум", score: 3, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_091": { id: "plant_091", name: "Орхидея Фаленопсис", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_092": { id: "plant_092", name: "Орхидея Цимбидиум", score: 3, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_093": { id: "plant_093", name: "Пальма Вашингтония Нитчатая", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_094": { id: "plant_094", name: "Пальма Камедорея", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_095": { id: "plant_095", name: "Пальма Лисий Хвост", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_096": { id: "plant_096", name: "Пальма Финик", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_097": { id: "plant_097", name: "Папая", score: 5, water: "frequent", light: "high", difficulty: "medium" },
  "plant_098": { id: "plant_098", name: "Папоротник Флебодиум", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_099": { id: "plant_099", name: "Папортние Платицериум Оленерогий", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_100": { id: "plant_100", name: "Папортник Птерис", score: 5, water: "moderate", light: "low", difficulty: "medium" },
  "plant_101": { id: "plant_101", name: "Паслен Рантонетти", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_102": { id: "plant_102", name: "Пассифлора", score: 6, water: "frequent", light: "high", difficulty: "medium" },
  "plant_103": { id: "plant_103", name: "Пахира", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_104": { id: "plant_104", name: "Педилантус", score: 7, water: "moderate", light: "high", difficulty: "easy" },
  "plant_105": { id: "plant_105", name: "Пеларгонии", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_106": { id: "plant_106", name: "Пеларгония Розебудная", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_107": { id: "plant_107", name: "Пеперомия Пикколо Банда", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_108": { id: "plant_108", name: "Пеперомия Россо", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_109": { id: "plant_109", name: "Пеперомия Туполистная Вариегатная", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_110": { id: "plant_110", name: "Пепино", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_111": { id: "plant_111", name: "Переския Годсеффа", score: 7, water: "moderate", light: "high", difficulty: "easy" },
  "plant_112": { id: "plant_112", name: "Перец Сычуанский", score: 7, water: "moderate", light: "high", difficulty: "medium" },
  "plant_113": { id: "plant_113", name: "Перец Черный", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_114": { id: "plant_114", name: "Пилея Пеперомиевидная", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_115": { id: "plant_115", name: "Плюмерия", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_116": { id: "plant_116", name: "Плющ Обыкновенный", score: 7, water: "moderate", light: "low", difficulty: "easy" },
  "plant_117": { id: "plant_117", name: "Рафидофора Тетрасперма", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_118": { id: "plant_118", name: "Розмарин", score: 7, water: "moderate", light: "high", difficulty: "easy" },
  "plant_119": { id: "plant_119", name: "Сансевиерия Фернвуд Микадо", score: 10, water: "rare", light: "any", difficulty: "easy" },
  "plant_120": { id: "plant_120", name: "Сарацения Stevensii", score: 6, water: "frequent", light: "high", difficulty: "medium" },
  "plant_121": { id: "plant_121", name: "Седеверия Гарри Баттерфилд", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_122": { id: "plant_122", name: "Седум Бурито", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_123": { id: "plant_123", name: "Синадениум", score: 7, water: "moderate", light: "high", difficulty: "easy" },
  "plant_124": { id: "plant_124", name: "Соландра", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_125": { id: "plant_125", name: "Спатифиллум", score: 7, water: "moderate", light: "low", difficulty: "easy" },
  "plant_126": { id: "plant_126", name: "Стефанотис", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_127": { id: "plant_127", name: "Такка Черная", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_128": { id: "plant_128", name: "Тамарилло", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_129": { id: "plant_129", name: "Текоманта", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_130": { id: "plant_130", name: "Тилландсия Ионанта", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_131": { id: "plant_131", name: "Традесканция Pink Hill", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_132": { id: "plant_132", name: "Традесканция Белоцветковая Albovittata", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_133": { id: "plant_133", name: "Традесканция Еллоу Хилл", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_134": { id: "plant_134", name: "Традесканция Зебрина", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_135": { id: "plant_135", name: "Традесканция Зебрина Квадриколор", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_136": { id: "plant_136", name: "Традесканция Нанук", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_137": { id: "plant_137", name: "Традесканция Рео Ситара Розовая", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_138": { id: "plant_138", name: "Традесканция Рео Ситара", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_139": { id: "plant_139", name: "Традесканция Рео", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_140": { id: "plant_140", name: "Традесканция Стыдливая Невеста", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_141": { id: "plant_141", name: "Традесканция Тайская", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_142": { id: "plant_142", name: "Тунбергия Мантия Короля", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_143": { id: "plant_143", name: "Фикус Бенгальский", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_144": { id: "plant_144", name: "Фикус Бенджамина", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_145": { id: "plant_145", name: "Фикус Каучуконосный", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_146": { id: "plant_146", name: "Фикус Пумила", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_147": { id: "plant_147", name: "Филодендрон Белый Рыцарь", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_148": { id: "plant_148", name: "Филодендрон Гитаровидный", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_149": { id: "plant_149", name: "Филодендрон Империал Ред", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_150": { id: "plant_150", name: "Филодендрон Карамель Марбл", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_151": { id: "plant_151", name: "Филодендрон Кобра", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_152": { id: "plant_152", name: "Филодендрон Краснеющий", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_153": { id: "plant_153", name: "Филодендрон Медуза", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_154": { id: "plant_154", name: "Филодендрон Меланохризум", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_155": { id: "plant_155", name: "Филодендрон Нэрроу", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_156": { id: "plant_156", name: "Филодендрон Розовая Принцесса", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_157": { id: "plant_157", name: "Филодендрон Село", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_158": { id: "plant_158", name: "Филодендрон Сканденс Миканс", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_159": { id: "plant_159", name: "Филодендрон Хастатум Сильвер Квин", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_160": { id: "plant_160", name: "Фиттония Серебристожильчатая", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_161": { id: "plant_161", name: "Фукия", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_162": { id: "plant_162", name: "Фуксия Пинк Галоре", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_163": { id: "plant_163", name: "Хавортия Аттенуата", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_164": { id: "plant_164", name: "Хавортия Купера", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_165": { id: "plant_165", name: "Хавортия Марумиана", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_166": { id: "plant_166", name: "Хавортия Оттянутая Энон.", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_167": { id: "plant_167", name: "Хатиора", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_168": { id: "plant_168", name: "Хлорофитум Оранж Грин", score: 8, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_169": { id: "plant_169", name: "Хлорофитум", score: 8, water: "moderate", light: "any", difficulty: "easy" },
  "plant_170": { id: "plant_170", name: "Хойя Карноза Альбомаргината", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_171": { id: "plant_171", name: "Хойя Эскимо", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_172": { id: "plant_172", name: "Цеперус", score: 6, water: "frequent", light: "high", difficulty: "medium" },
  "plant_173": { id: "plant_173", name: "Церопегия Вуда", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_174": { id: "plant_174", name: "Циссус Антарктический", score: 7, water: "moderate", light: "low", difficulty: "easy" },
  "plant_175": { id: "plant_175", name: "Шинус Мягкий Перец Роовый", score: 7, water: "moderate", light: "high", difficulty: "medium" },
  "plant_176": { id: "plant_176", name: "Шлюмберга", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_177": { id: "plant_177", name: "Эониум Медуза", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_178": { id: "plant_178", name: "Эпипремнум Золотистый", score: 8, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_179": { id: "plant_179", name: "Эпипремнум Н Джой", score: 8, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_180": { id: "plant_180", name: "Эписция Акварельная", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_181": { id: "plant_181", name: "Эпифиллум", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_182": { id: "plant_182", name: "Эритрина Петушиный Гребень", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_183": { id: "plant_183", name: "Эсхинантус Мона Лиза", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_184": { id: "plant_184", name: "Эхеверия Горбатоцветная Куананская", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_185": { id: "plant_185", name: "Эхеверия Рунделли Кристата", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_186": { id: "plant_186", name: "Эхиверия Crispate Beauty", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_187": { id: "plant_187", name: "Эчеверия Лилацина", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_188": { id: "plant_188", name: "Юкка Глориоза Вариегата", score: 8, water: "moderate", light: "high", difficulty: "easy" },
  "plant_189": { id: "plant_189", name: "Фуксия", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_190": { id: "plant_190", name: "Замиокулькас Рейвен", score: 10, water: "rare", light: "low", difficulty: "easy" },
  "plant_191": { id: "plant_191", name: "Антуриум Кларинервиум", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_192": { id: "plant_192", name: "Кросандра", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_193": { id: "plant_193", name: "Опунция Обыкновенная", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_194": { id: "plant_194", name: "Роза Кордана", score: 5, water: "moderate", light: "high", difficulty: "medium" },
  "plant_195": { id: "plant_195", name: "Сансевиерия", score: 10, water: "rare", light: "any", difficulty: "easy" },
  "plant_196": { id: "plant_196", name: "Сциндаптус Пиктус", score: 8, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_197": { id: "plant_197", name: "Хойя Керри", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_198": { id: "plant_198", name: "Пеларгониия Зональная", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_199": { id: "plant_199", name: "Пеларгония Зональная", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_200": { id: "plant_200", name: "Драцена Деремская", score: 7, water: "moderate", light: "low", difficulty: "easy" },
  "plant_201": { id: "plant_201", name: "Эхеверия Crispate Beauty", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_202": { id: "plant_202", name: "Драцена", score: 7, water: "moderate", light: "low", difficulty: "easy" },
  "plant_203": { id: "plant_203", name: "Филодендрон Краснеющий", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_204": { id: "plant_204", name: "Бамбук", score: 5, water: "frequent", light: "medium", difficulty: "medium" },
  "plant_205": { id: "plant_205", name: "Фикус Бенджамина", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_206": { id: "plant_206", name: "Фиттония Вершаффельта Красная", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_207": { id: "plant_207", name: "Каланхоэ Дегремона", score: 7, water: "moderate", light: "high", difficulty: "easy" },
  "plant_208": { id: "plant_208", name: "Бегония Рекс Маори Хейз", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_209": { id: "plant_209", name: "Бегония Рекс Рочеарт", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_210": { id: "plant_210", name: "Фикус Каучуконосный", score: 6, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_211": { id: "plant_211", name: "Орхидея Цимбидиум", score: 3, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_212": { id: "plant_212", name: "Пеларгония Тюльпановидная", score: 6, water: "moderate", light: "high", difficulty: "medium" },
  "plant_213": { id: "plant_213", name: "Седум Нуссбаумерианум", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_214": { id: "plant_214", name: "Шлюмберга", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_215": { id: "plant_215", name: "Шлюмберга", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_216": { id: "plant_216", name: "Шлюмберга", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_217": { id: "plant_217", name: "Алоэ Вера Пятнистое", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_218": { id: "plant_218", name: "Алоэ Древовидное", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_219": { id: "plant_219", name: "Эпифиллум Аккермана", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_220": { id: "plant_220", name: "Шлюмберга", score: 7, water: "moderate", light: "medium", difficulty: "easy" },
  "plant_221": { id: "plant_221", name: "Папортник Циатея Австралис", score: 5, water: "moderate", light: "low", difficulty: "medium" },
  "plant_222": { id: "plant_222", name: "Филодендрон Империал Ред", score: 5, water: "moderate", light: "medium", difficulty: "medium" },
  "plant_223": { id: "plant_223", name: "Аглаонема Мария", score: 6, water: "moderate", light: "low", difficulty: "medium" },
  "plant_224": { id: "plant_224", name: "Алоказия Кукулата", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_225": { id: "plant_225", name: "Антуриум Сильвер Блаш", score: 4, water: "moderate", light: "medium", difficulty: "hard" },
  "plant_226": { id: "plant_226", name: "Красула Blue Wave", score: 8, water: "rare", light: "high", difficulty: "easy" },
  "plant_227": { id: "plant_227", name: "Трихоцереус Кактус", score: 9, water: "rare", light: "high", difficulty: "easy" },
  "plant_228": { id: "plant_228", name: "Филодендрон Биркин", score: 5, water: "moderate", light: "medium", difficulty: "medium" }
};

// Полный список всех классифицированных растений (228 штук!)
const ALL_CLASSIFIED_PLANTS = Object.values(PLANT_SURVIVAL_CLASSIFICATION);

// Функция для получения случайного описания растения
function getRandomPlantDescription() {
  const descriptions = [
    "Этот железный боец готов терпеть вашу забывчивость",
    "Растение-ниндзя: выживает там, где другие сдаются",
    "Выживет даже если вы забудете, что оно у вас есть",
    "Идеально для тех, кто поливает растения раз в полгода",
    "Растение, которое не сдастся без боя",
    "Ваш личный зеленый спецназовец",
    "Выживальщик с большим стажем",
    "Не требует внимания, только восхищения",
    "Растение для настоящих ленивых садоводов",
    "Мы нашли растение, которое готово мириться с вашими недостатками!",
    "Бронированный танк среди растений — пули не берут",
    "Его девиз: 'Полив? Не, не слышал'",
    "Выдержит ядерную зиму и вашу забывчивость одновременно",
    "Зеленый терпила с железными нервами",
    "Любит, когда его забывают — так он чувствует себя особенным",
    "Поливать можно по праздникам и дням рождения",
    "Идеален для тех, кто уверен, что у них 'тяжелая рука'",
    "Переживет ваш переезд, ремонт и три кризиса личности",
    "Единственное, что выживет после вашего отпуска",
    "Фотосинтезирует даже при свете экрана ноутбука",
    "Мутация 'неубиваемости' достигла максимального уровня",
    "Запасает воду лучше верблюда в пустыне",
    "Стоик в мире растений — молча страдает, но живет",
    "Зеленый оптимист: 'Сегодня без воды? Зато завтра может быть!'",
    "Уровень выносливости: 99/100 — почти неуязвим"
  ];
  return descriptions[Math.floor(Math.random() * descriptions.length)];
}

// Экспорт для использования в основном приложении
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    PLANT_SURVIVAL_CLASSIFICATION,
    ALL_CLASSIFIED_PLANTS,
    getRandomPlantDescription
  };
}